name: Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - run: |
          git remote add upstream https://github.com/ACL4SSR/ACL4SSR.git

      - run: |
          git fetch upstream master

      - run: |
          git merge upstream/master --no-edit

      - run: |
          git push origin master
